/**
 * Every i18n pinning test in this tree builds its bundle by merging whatever
 * findModuleEnglishBundles() finds under Mnemo.Infrastructure/Modules. A directory move once
 * pointed that walk at a tree with nothing in it: the tests built from a hardcoded key list
 * failed loudly, but the ones generated by it.each over a bundle-derived list produced zero
 * cases and vanished from the run instead of failing it, so the suite quietly reported fewer
 * tests with no failure at all. This pins a floor under the walk itself so an empty, or
 * near-empty, result fails here, out loud, before it can hide as a smaller total elsewhere.
 */
import { describe, expect, it } from "vitest"

import { findModuleEnglishBundles } from "./test-bundle"

describe("findModuleEnglishBundles", () => {
  it("finds a non-trivial number of module bundles", () => {
    // Ten modules carry a Translations/en.json today. A regression that walked the wrong
    // tree, or an empty one, would make every it.each built from this list vanish instead
    // of fail, so the floor sits well under that count rather than merely above zero.
    expect(findModuleEnglishBundles().length).toBeGreaterThan(7)
  })
})
