/**
 * Differential test: replays a fixture of C#-generated cases through the TS
 * port and asserts byte-exact agreement. Since C#/JS/DOM strings are all
 * UTF-16, this comparison is exact, not approximate -- any divergence here is
 * a real behavioral difference between the two implementations, not a
 * precision artifact.
 *
 * The fixture itself is generated by Mnemo.SpanFixtureGen (a console project
 * referenced from MnemoApp.sln, so a solution build catches breakage against
 * Mnemo.Core early) from a fixed SplitMix64 seed, so it is reproducible byte
 * for byte. It ships gzip-compressed (span-diff.json.gz, ~6000 cases would
 * otherwise be several MB of committed JSON) and is gunzipped here at load
 * time with Node's built-in zlib -- no new dependency. To regenerate, from
 * the repo root in PowerShell:
 *
 *   dotnet run --project Mnemo.SpanFixtureGen -p:OutDir=<scratch>\
 *
 * Regenerate only when InlineSpanFormatApplier / InlineSpanText / InlineAutoLink
 * (Mnemo.Core/Formatting) or their TS counterparts (spans.ts/format.ts/autolink.ts)
 * intentionally change behavior. Never regenerate to make a failing case here
 * pass -- a divergence between the fixture and the TS port means one of the
 * two implementations has a bug, and loosening the fixture only hides it.
 */

/// <reference types="node" />

import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { describe, expect, it } from 'vitest';

import { applyAutoLink } from './autolink';
import {
  applyFormat,
  applyTextEdit,
  forceSubSup,
  rangeHasFormat,
  replaceRange,
  sliceSpans,
  splitAt,
  type InlineFormat,
} from './format';
import { caretLength, flattenDisplay, flattenForCaret, normalizeSpans } from './spans';
import type { InlineSpan } from './types';
import { parseSpans } from './wire';

interface FixtureCase {
  index: number;
  op: string;
  spans: unknown[];
  args: Record<string, unknown>;
  expected: { spans?: unknown[]; value?: string | number | boolean };
}

interface Fixture {
  seed: number;
  casesPerOp: number;
  operations: string[];
  caseCount: number;
  cases: FixtureCase[];
}

const fixturePath = path.resolve(import.meta.dirname, 'fixtures/span-diff.json.gz');
const fixtureJson = zlib.gunzipSync(fs.readFileSync(fixturePath)).toString('utf-8');
const fixture: Fixture = JSON.parse(fixtureJson);

type OpResult = InlineSpan[] | string | number | boolean;

function runOp(c: FixtureCase): OpResult {
  const spans = parseSpans(c.spans);
  const start = c.args.start as number;
  const end = c.args.end as number;
  const kind = c.args.kind as InlineFormat;
  const color = (c.args.color as string | null | undefined) ?? null;

  switch (c.op) {
    case 'normalizeSpans':
      return normalizeSpans(spans);
    case 'flattenDisplay':
      return flattenDisplay(spans);
    case 'flattenForCaret':
      return flattenForCaret(spans);
    case 'caretLength':
      return caretLength(spans);
    case 'sliceSpans':
      return sliceSpans(spans, start, end);
    case 'splitAt':
      return splitAt(spans, start, end);
    case 'rangeHasFormat':
      return rangeHasFormat(spans, start, end, kind, color);
    case 'replaceRange':
      return replaceRange(spans, start, end, parseSpans(c.args.insertion as unknown[]));
    case 'forceSubSup':
      return forceSubSup(spans, start, end, c.args.sub as boolean, c.args.sup as boolean);
    case 'applyFormat':
      return applyFormat(spans, start, end, kind, color);
    case 'applyTextEdit':
      return applyTextEdit(spans, c.args.oldText as string, c.args.newText as string);
    case 'applyAutoLink':
      return applyAutoLink(spans);
    default:
      throw new Error(`differential fixture: unknown op "${c.op}"`);
  }
}

function expectedValue(c: FixtureCase): OpResult {
  return c.expected.spans !== undefined ? parseSpans(c.expected.spans) : c.expected.value!;
}

/**
 * The one deliberate, documented behavioral divergence from Mnemo.Core:
 * `applyEquation` (format.ts) builds a merged equation's latex from the
 * selection's *display* text, not the caret-space flatten C# uses there --
 * see the comment on `applyEquation` for why the caret-space flatten is
 * wrong (it would splice an atom's placeholder character into real latex).
 *
 * Keyed by fixture case `index`, not by op/kind, so this can never silently
 * absorb an unrelated `applyFormat` regression -- only these exact fixture
 * cases (stable for this fixture's seed) are exempted, and the shape check
 * below throws if a fixture regen ever reassigns these indices to a
 * different kind of case.
 */
const KNOWN_DIVERGENT_CASES: ReadonlyMap<number, string> = new Map([
  [4606, 'applyEquation uses flattenDisplay instead of the caret-space flatten'],
  [4884, 'applyEquation uses flattenDisplay instead of the caret-space flatten'],
]);

/** A toEqual() diff on a 20-span object is unreadable; spell out exactly what diverged and how to reproduce it. */
function diagnose(c: FixtureCase, actual: OpResult, expected: OpResult, cause: unknown): never {
  throw new Error(
    [
      `Differential mismatch: case ${c.index} (op="${c.op}", fixture seed=${fixture.seed})`,
      `input spans: ${JSON.stringify(c.spans)}`,
      `args: ${JSON.stringify(c.args)}`,
      `expected (from C#): ${JSON.stringify(expected)}`,
      `actual (from TS):   ${JSON.stringify(actual)}`,
      `regenerate with: dotnet run --project Mnemo.SpanFixtureGen -p:OutDir=<scratch>\\`,
    ].join('\n'),
    { cause },
  );
}

describe(`inline-span differential vs Mnemo.Core (seed ${fixture.seed}, ${fixture.caseCount} cases)`, () => {
  it('fixture header is well-formed', () => {
    expect(fixture.cases.length).toBe(fixture.caseCount);
    expect(fixture.caseCount).toBeGreaterThanOrEqual(1000);
  });

  const byOp = new Map<string, FixtureCase[]>();
  for (const c of fixture.cases) {
    const list = byOp.get(c.op) ?? [];
    list.push(c);
    byOp.set(c.op, list);
  }

  for (const op of fixture.operations) {
    const cases = byOp.get(op) ?? [];
    describe(`${op} (${cases.length} cases)`, () => {
      it.each(cases)('case $index', (c) => {
        const knownReason = KNOWN_DIVERGENT_CASES.get(c.index);
        if (knownReason !== undefined) {
          if (c.op !== 'applyFormat' || c.args.kind !== 'equation') {
            throw new Error(
              `case ${c.index} is allowlisted as the equation divergence but is op="${c.op}" ` +
                `kind="${String(c.args.kind)}" -- the fixture changed shape under this index; ` +
                `update or remove the allowlist entry rather than let it cover a different case`,
            );
          }
          const actual = runOp(c);
          const expected = expectedValue(c);
          // The divergence must still be present. If this ever passes, the
          // deliberate behavior changed (or reverted) and the allowlist
          // entry is stale -- remove it rather than leaving a dead exemption.
          expect(
            actual,
            `case ${c.index} now matches C# -- remove its KNOWN_DIVERGENT_CASES entry (${knownReason})`,
          ).not.toEqual(expected);
          return;
        }

        const actual = runOp(c);
        const expected = expectedValue(c);
        try {
          expect(actual).toEqual(expected);
        } catch (err) {
          diagnose(c, actual, expected, err);
        }
      });
    });
  }
});
