// Regenerates src/styles/tokens.css from the Avalonia reference theme resources
// (../Mnemo.UI/Themes/Core). Run with: node tools/gen-tokens.mjs
//
// Colors are read from each theme's Colors.axaml, converted from Avalonia
// #AARRGGBB to CSS #RRGGBBAA, and emitted as semantic CSS custom properties
// (Dawn -> :root, the rest -> [data-theme] overrides for keys that differ).
// The scale/layout header below is hand-maintained here so the whole file has a
// single source of truth.

import fs from 'node:fs'
import path from 'node:path'

const SCRIPT_DIR = import.meta.dirname
const THEMES_DIR = path.resolve(SCRIPT_DIR, '../../Mnemo.UI/Themes/Core')
const OUT_PATH = path.resolve(SCRIPT_DIR, '../src/styles/tokens.css')
const THEMES = ['Dawn', 'Dusk', 'Ember', 'Noon'] // Dawn = default/base

function kebab(key) {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Za-z])(\d)/g, '$1-$2')
    .replace(/(\d)([A-Za-z])/g, '$1-$2')
    .toLowerCase()
}

// Avalonia colors are #AARRGGBB (8-digit) or #RRGGBB (6). CSS wants #RRGGBBAA.
function toCss(value) {
  const v = value.trim()
  if (/^transparent$/i.test(v)) return 'transparent'
  const m8 = /^#([0-9a-fA-F]{2})([0-9a-fA-F]{6})$/.exec(v)
  if (m8) return ('#' + m8[2] + m8[1]).toLowerCase()
  const m6 = /^#([0-9a-fA-F]{6})$/.exec(v)
  if (m6) return v.toLowerCase()
  return v // named color (unexpected beyond transparent)
}

function parseColors(file) {
  const text = fs.readFileSync(file, 'utf-8')
  const re = /<Color\s+x:Key="([^"]+)"\s*>([^<]*)<\/Color>/g
  const out = new Map()
  let m
  while ((m = re.exec(text)) !== null) out.set(m[1], m[2])
  return out
}

const parsed = {}
for (const t of THEMES) parsed[t] = parseColors(path.join(THEMES_DIR, t, 'Colors.axaml'))

const base = parsed.Dawn
const baseKeys = [...base.keys()]

function block(selector, values, onlyIfDiff) {
  const lines = [`${selector} {`]
  for (const k of baseKeys) {
    if (!values.has(k)) continue
    const css = toCss(values.get(k))
    if (onlyIfDiff && toCss(base.get(k)) === css) continue
    lines.push(`  --${kebab(k)}: ${css};`)
  }
  lines.push('}')
  return lines.join('\n')
}

const HEADER = `/*
 * Mnemo design tokens. GENERATED by tools/gen-tokens.mjs - do not edit by hand;
 * edit the generator or the source Avalonia themes (../Mnemo.UI/Themes/Core) and
 * re-run \`node tools/gen-tokens.mjs\`.
 *
 * Colors are semantic tokens ported 1:1 from the reference themes, redefined per
 * theme via [data-theme]; the theme-independent scale/layout tokens live once in
 * :root. 8-digit Avalonia #AARRGGBB values are converted to CSS #RRGGBBAA. These
 * are plain custom properties (not @theme), so they are always available as
 * var(--token); index.css maps the subset that needs Tailwind utilities.
 */

/* ---- Fonts (self-hosted; the webview is offline, no CDN) ---- */
@font-face { font-family: "Geist"; font-weight: 300; font-style: normal; font-display: swap; src: url("/fonts/Geist-Light.ttf") format("truetype"); }
@font-face { font-family: "Geist"; font-weight: 400; font-style: normal; font-display: swap; src: url("/fonts/Geist-Regular.ttf") format("truetype"); }
@font-face { font-family: "Geist"; font-weight: 500; font-style: normal; font-display: swap; src: url("/fonts/Geist-Medium.ttf") format("truetype"); }
@font-face { font-family: "Geist"; font-weight: 600; font-style: normal; font-display: swap; src: url("/fonts/Geist-SemiBold.ttf") format("truetype"); }
@font-face { font-family: "Geist"; font-weight: 700; font-style: normal; font-display: swap; src: url("/fonts/Geist-Bold.ttf") format("truetype"); }
@font-face { font-family: "Geist"; font-weight: 800; font-style: normal; font-display: swap; src: url("/fonts/Geist-ExtraBold.ttf") format("truetype"); }
@font-face { font-family: "Geist Mono"; font-weight: 400; font-style: normal; font-display: swap; src: url("/fonts/GeistMono-Regular.ttf") format("truetype"); }
@font-face { font-family: "STIX Two Math"; font-weight: 400; font-style: normal; font-display: swap; src: url("/fonts/STIXTwoMath-Regular.ttf") format("truetype"); }

/* ---- Theme-independent scale + layout tokens ---- */
:root {
  /* Font families */
  --font-sans: "Geist", "Segoe UI", Arial, sans-serif;
  --font-mono: "Geist Mono", ui-monospace, "Cascadia Mono", monospace;
  --font-math: "STIX Two Math", "Cambria Math", serif;

  /* Corner radius scale */
  --radius-sm: 6px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-xl: 16px;
  --radius-pill: 999px;

  /* Font sizes */
  --font-size-heading-1: 32px;
  --font-size-heading-2: 28px;
  --font-size-heading-3: 24px;
  --font-size-heading-4: 20px;
  --font-size-heading-5: 18px;
  --font-size-heading-6: 16px;
  --font-size-body-large: 18px;
  --font-size-body-medium: 16px;
  --font-size-body-small: 14px;
  --font-size-body-extra-small: 12px;
  --font-size-stat-hero: 36px;
  --font-size-caption: 11px;
  --font-size-body-caption: 11px;
  --font-size-caption-button: 10px;
  --font-size-tooltip: 12px;
  --font-size-micro: 9px;

  /* Elevation (shadow only; pair with a theme surface color) */
  --elevation-1: 0 1px 2px 0 #00000014;
  --elevation-2: 0 2px 8px 0 #0000001f;
  --elevation-3: 0 8px 24px 0 #00000029;
  --elevation-4: 0 16px 48px -4px #0000003d;

  /* Spacing scale (4px grid) */
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 20px;
  --space-6: 24px;
  --space-7: 32px;
  --space-8: 40px;

  /* Icon sizes */
  --icon-size-sm: 16px;
  --icon-size-md: 20px;
  --icon-size-lg: 24px;
  --icon-size-xl: 32px;

  /* Standard insets (Avalonia Thickness -> CSS shorthand) */
  --page-padding: 24px 40px;
  --pane-padding: 20px;
  --card-padding: 16px;
  --list-row-padding: 10px 12px;

  /* Sidebar / topbar dimensions */
  --sidebar-width: 264px;
  --sidebar-collapsed-width: 64px;
  --sidebar-inset: 10px 14px 12px 14px;
  --topbar-height: 44px;
  --topbar-inset: 0 14px 0 20px;
  --topbar-search-width: 230px;
}

/* ---- Per-theme semantic colors (generated from Colors.axaml) ---- */
`

let css = HEADER + '\n'
css += block(':root,\n[data-theme="dawn"]', base, false) + '\n\n'
for (const t of THEMES.slice(1)) {
  css += block(`[data-theme="${t.toLowerCase()}"]`, parsed[t], true) + '\n\n'
}

fs.writeFileSync(OUT_PATH, css)

// Report to stderr so stdout stays clean.
console.error(`Dawn: ${base.size} keys`)
for (const t of THEMES.slice(1)) {
  const missing = baseKeys.filter((k) => !parsed[t].has(k))
  console.error(`${t}: ${parsed[t].size} keys; inherits-from-Dawn=${missing.length}${missing.length ? ' [' + missing.join(', ') + ']' : ''}`)
}
console.error(`Wrote ${OUT_PATH}`)
